language: node_js
node_js:
  - '5.0'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-linters' ]; then cd .. && eval "mv $currentfolder generator-linters" && cd generator-linters; fi
